version: '3'

services:
  pulsar:
    command: /bin/sh -c "bin/apply-config-from-env.py conf/standalone.conf && bin/pulsar standalone"
    image: apachepulsar/pulsar:2.5.0
    ports:
      - "6650:6650"
      - "8080:8080"
    volumes:
      - pulsardata:/pulsar/data
      - pulsarconf:/pulsar/conf
    networks:
      - local-pulsar-net

volumes:
  pulsardata:
  pulsarconf:

networks:
  local-pulsar-net:
