version: '3.3'

services:
  pubsub:
    image: adhawk/google-pubsub-emulator
    ports:
      - 8085:8085
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8085"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  app-network:
    external: false
