coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 2%
    patch:
      default:
        target: 80%
        threshold: 1%

flag_management:
  individual_flags:
    - name: unittests
      statuses:
        - type: patch
          target: 60%
          threshold: 2%
    - name: integration
      statuses:
        - type: patch
          target: auto
          threshold: 1%