version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
      time: "04:00"
      timezone: Asia/Calcutta
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor"]
    assignees:
      - "shivasishdas"
    reviewers:
      - "sunnyagg"
      - "shivasishdas"

