type: google.api.Service
config_version: 3

http:
  rules:
    - selector: rzp.common.health.v1.HealthCheckAPI.Check
      get: "/v1/healthcheck"
    - selector: rzp.metro.producer.v1.ProducerApi.Produce
      post: "/v1/produce"
      body: "*"
