[app]
    appEnv                = "prod"
    serviceName           = "metro"
    shutdownTimeout       = 2
    shutdownDelay         = 2
    gitCommitHash         = "nil"
[tracing]
    serviceName           = "metro"
    logSpans              = false
    host                  = "localhost"
    port                  = "6831"
    disabled              = false
[sentry]
    appName               = "metro"
    dsn                   = "dummy"
    mock                  = true
    errorLevel            = 1

[web]
    [web.broker]
        variant               = "kafka"
        [web.broker.brokerconfig]
            brokers       = ["localhost:9092"]
            enableTLS     = true
            certDir       = "/app/configs/"
            [web.broker.brokerconfig.admin]
                enableTopicCleanUp = true
    [web.interfaces]
        [web.interfaces.api]
            GrpcServerAddress               = "0.0.0.0:8081"
            HttpServerAddress               = "0.0.0.0:8082"
            InternalHttpServerAddress       = "0.0.0.0:9000"

[worker]
    [worker.broker]
        variant               = "kafka"
        [worker.broker.brokerconfig]
            brokers       = ["localhost:9092"]
            enableTLS     = true
            certDir       = "/app/configs/"
    [worker.interfaces]
        [worker.interfaces.api]
            GrpcServerAddress               = "0.0.0.0:8083"
            HttpServerAddress               = "0.0.0.0:8084"
            InternalHttpServerAddress       = "0.0.0.0:9001"
    [worker.httpclientconfig]
            connectTimeoutMs        = 10000
            connKeepAliveMs         = 0
            expectContinueTimeoutMs = 0
            idleConnTimeoutMs       = 60000
            maxAllIdleConns         = 1000
            maxHostIdleConns        = 1000
            responseHeaderTimeoutMs = 25000
            tlsHandshakeTimeoutMs   = 2000
    [worker.schedulerconfig]
            nodeBindingRefreshIntervalMins = 60

[registry]
    driver                    = "consul"
    [registry.consulconfig]
        [registry.consulconfig.config]
            address            = "localhost:8500"
            token              = ""
            scheme             = "https"
            caPem              = ""

[cache]
    driver                    = "redis"
    [cache.consulconfig]
        [cache.consulconfig.config]
            address            = "localhost:8500"
            token              = ""
            scheme             = "http"
            caPem              = ""

[openAPIServer]
    httpServerAddress     = "0.0.0.0:3000"
    proxyHostAddress      = "0.0.0.0:8082"
    scheme                = "http"

[admin]
    username = ""
    password = ""

[encryption]
    key = ""
