#!/bin/sh

# This script does not handle file names that contain spaces.

gofiles=$(git diff --cached --name-only --diff-filter=ACM | grep -v vendor | grep '.go$')
[ -z "$gofiles" ] && exit 0

unformatted=$(goimports -l $gofiles)
[ -z "$unformatted" ] && exit 0

# Some files are not goimport'd. Print message and fail.

echo >&2 "Go files must be formatted with goimports. Please run:"
for fn in $unformatted; do
	echo >&2 "  goimports -w $PWD/$fn"
done

exit 1