on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        continue-on-error: false
        name: Build
        steps:
            - name: checkout
              id: checkout
              uses: actions/checkout@v2
            - name: build
              uses: docker/build-push-action@v1
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
                repository: razorpay/metro
                tags: ${{ github.sha }}
                dockerfile: build/docker/Dockerfile

