name: ReviewDog CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  reviewdog:
    name: Run reviewdog
    runs-on: ubuntu-latest
    container: golang:1.16.5-alpine3.13
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: install prerequisites
        run: |
          apk add --update --no-cache --repository https://dl-4.alpinelinux.org/alpine/latest-stable/community/ build-base gcc make git librdkafka-dev pkgconf curl bash
      - name: setup
        run: |
          make deps proto-generate mock-gen
          go mod vendor
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          golangci_lint_flags:  "-v --config=.github/.golangci.yml"
          reporter: github-pr-review
          github_token : ${{ secrets.GITHUB_TOKEN }}
