name: ReviewDog CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  reviewdog:
    name: Run reviewdog
    runs-on: [ self-hosted ]
    container: 
      image: c.rzp.io/proxy_dockerhub/golang:1.16.5-alpine3.13
      credentials:
        username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
        password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
      volumes:
        - /etc/hosts:/etc/hosts
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v2
      - name: install prerequisites
        run: |
          apk add --update --no-cache --repository https://dl-4.alpinelinux.org/alpine/latest-stable/community/ build-base gcc make git librdkafka-dev pkgconf curl bash sudo
      - name: setup
        run: |
          make deps proto-generate mock-gen
          go mod vendor
      - name: Target repo permission update # Workaround for CVE-2022-24765  
        run: |
          chown -R root:root $GITHUB_WORKSPACE
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          golangci_lint_flags:  "-v --build-tags=musl --config=.github/.golangci.yml"
          reporter: github-pr-review
          github_token : ${{ secrets.GITHUB_TOKEN }}
