name: SecurityChecks
on:
  workflow_dispatch:
  pull_request: { }
  push:
    branches: [ "master" ]
  schedule:
    - cron: '30 20 * * *'
jobs:
  security-sast:
    uses: razorpay/security-action/.github/workflows/semgrep.yml@master
    secrets:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

  security-imagescan-api:
    uses: razorpay/security-action/.github/workflows/image_scan.yml@master
    with:
      TRIVY_IMAGE_REF: c.rzp.io/razorpay/metro:api
      BU: payments
      IMAGE_TYPE: ${{ github.sha }}
    secrets:
      HARBOR_DOCKER_USERNAME: ${{ secrets.HARBOR_DOCKER_USERNAME }}
      HARBOR_DOCKER_PASSWORD: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
      BHADRA_TOKEN: ${{ secrets.BHADRA_TOKEN }}
      DOCKER_IMAGE_INIT_COMMAND: c.rzp.io/razorpay/metro:${{ github.sha }} --build-arg GIT_COMMIT_HASH=${{ github.sha }} --build-arg GIT_TOKEN=${{ secrets.GIT_TOKEN }} --build-arg GIT_USERNAME=rzp -f build/docker/Dockerfile
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      SLACK_HOOK: ${{ secrets.SLACK_HOOK }}

  security-statuscheck:
    needs: [ security-sast ]
    if: always()
    uses: razorpay/security-action/.github/workflows/status_check.yml@master
    with:
      WORKFLOW_RESULT: ${{ needs.security-sast.result == 'success' && needs.security-sast.result != 'cancelled' || 'false' }}
